.PHONY: build certs run test

# build compiles the webhook binary into bin/webhook.
build:
	go build -o bin/webhook ./webhook/

# certs generates a self-signed CA and server TLS certificate pair under certs/.
# Run this once before `make run` or deploying to a cluster.
certs:
	bash certs/gen-certs.sh

# run starts the webhook server using the certs generated by `make certs`.
# The server listens on :8443.
run:
	TLS_CERT=certs/tls.crt TLS_KEY=certs/tls.key ./bin/webhook

# test runs the Go test suite for the webhook package.
test:
	go test ./webhook/...
